### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by mxstbr** [flokosiol/kirby-sharingbuttons#1]
Can we maybe integrate PHP output back into the http://sharingbuttons.io website? So you could choose between HTML and PHP output, which might be usable in Kirby and Wordpress and many more?

**Comment by flokosiol** [comment]
Thanks for your feedback, Max. But I'm not sure, if I understand you right. 

The Kirby plugin is just a wrapper which translates a (Kirby specific) configuration into the HTML output as shown on sharingbuttons.io. I'm quite sure this can't be transformed to an abstract PHP version which then could be used for both, Kirby and Wordpress.
